export const columnsOrder = [
  {
    field: 'code',
    filter: 'text',
    filterable: true,
    hidden: false,
    title: 'Năm học',
    width: 80,
  },
  {
    field: 'firstSemesterStartDate',
    type: 'date',
    format: true,
    filter: 'date',
    filterable: true,
    hidden: false,
    title: 'Ngày bắt đầu học kì I',
    width: 80,
  },
  {
    field: 'firstSemesterEndDate',
    type: 'date',
    format: 'fdshgfjhk',
    filter: 'date',
    filterable: true,
    hidden: false,
    title: 'Ngày kết thúc học kì I',
    width: 80,
  },

  {
    field: 'secondSemesterStartDate',
    type: 'date',
    format: true,
    filter: 'date',
    filterable: true,
    hidden: false,
    title: 'Ngày bắt đầu học kì II',
    needTemplate: true,
    width: 80,
  },
  {
    field: 'secondSemesterEndDate',
    type: 'date',
    format: true,
    filter: 'date',
    filterable: true,
    hidden: false,
    title: 'Ngày kết thúc học kì II',
    width: 80,
  },
  {
    title: 'Thao tác',
    filterable: false,
    hidden: false,
    needTemplate: true,
    width: 60,
  },
];
